### ISSUE TITLE
Version 1 Checklist

### ISSUE THREAD

**Issue by armcburney** [AndrewMcBurney/engfair#1]
### Frontend
- [x] Pictures from past events for hero banner
- [x] Professional Icons
- [x] EngSoc logo
- [x] Contact Form
- [x] Sign-up Form

### Backend
- [x] Send emails on contact form submission

### Website Content
- [x] The Waterloo Advantage spiel
- [x] Event Details text

### Other
- [x] Metas for SEO, Facebook, Twitter (for promotion)
- [x] Force ssl
- [x] Domain (engcareerfair.com)
- [x] Hosting on Heroku

**Comment by armcburney** [comment]
v1 Done 🎉
